### ISSUE TITLE
Upgrade to akeneo 3.0.x

### ISSUE THREAD

**Issue by kazuparis** [basecom/akeneo-rulesUI#11]
Hello there,

Do you plan to upgrade this extension to the last akeneo version?
Thank you for your time.

Kind regards
Sylvain

**Comment by jkniest** [comment]
Hello Sylvain,

thanks for your interest. We are planning on releasing the akeneo-rulesUI for Akeneo 3.0 in the next days. I will keep you informed.

Have a nice day
Jordan

**Comment by kazuparis** [comment]
Hello Jordan,

Thank you for this information. If you need some help during your tests feel free to ask. We could try to find some time to give you a hand.

Sylvain

**Comment by jkniest** [comment]
Hey,

Sorry it took a while. The update to akeneo 3.0.* is currently in internal code review. You may already test all changes in the 3.0 branch.

When the code review is finished (probably tomorrow) we will release the new version. I'll keep you informed.

**Comment by kazuparis** [comment]
Hi Jordan,

Thank you for your time on this. I will go it a try in the following days. 
Have a good day.

**Comment by jkniest** [comment]
I have tagged the 3.0.0 release! Please let me know, if you have any problems.

Thanks!
