### ISSUE TITLE
Impossible to install with composer

### ISSUE THREAD

**Issue by bOnepain** [basecom/akeneo-rulesUI#5]
Hello,
First of all, thanks for that great job that will ease my customer.
But, the problem is I cannot manage to install this bundle with composer since it seems to be lacking stability information in composer.json

> $ composer require basecom/akeneo-rulesUI
>
> [InvalidArgumentException]                                                                                                                              
>  Could not find package basecom/akeneo-rulesUI at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability 

Or I might be missing something.

**Comment by Schwierig** [comment]
Hi bOnepain,
I need to do some changes in our composer.json and submitted the bundle to packagist. You should be able to install our bundle now by running:

`composer require basecom/akeneo-rules-ui`

I'm sorry for any inconvenience caused by this issue.

Greetings,
Schwierig

**Comment by bOnepain** [comment]
Thank you, I've been able to install the bundle.

Greetings
Benoit
