### ISSUE TITLE
Upgrade to akeneo 2.2

### ISSUE THREAD

**Issue by muspelheim** [basecom/akeneo-rulesUI#7]
Hi all, do you planned upgrade this package to latest version of akeneo?

**Comment by Schwierig** [comment]
Hi, we are working on it currently. I will keep you updated.

Greetings

**Comment by Schwierig** [comment]
After testing the bundle in 2.2 we didn't encounter any problems and pushed the 2.2 tag. If you get any errors anyhow please be sure to report them here.
