### ISSUE TITLE
Upgrade to akeneo 2.3

### ISSUE THREAD

**Issue by muspelheim** [basecom/akeneo-rulesUI#8]
Hi, could you add new dependency rule for akeneo 2.3. as i saw this version have not any break changes related with your package. Will be very good to use your package with latest akeneo versions.

**Comment by Schwierig** [comment]
Hi, since Akeneo 2.3 isn't released officially yet we didn't plan on releasing a new version. But I will push one when I got some free time in the next days.

Greetings,
Amir

**Comment by jkniest** [comment]
The rules ui is available for 2.3 and in a few days also for 3.0. So I'm closing the issue.
